### ISSUE TITLE
AWS - npm ERR! nospc ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by Cris-FPAZ** [UBC-CIC/health-platform#25]
![image](https://user-images.githubusercontent.com/109387254/185252520-1ac018e0-73ef-4961-8615-2e7a1496d5ee.png)

[cloudshell-user@ip-10-0-180-32 ~]$ npm install -g @aws-amplify/cli
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
[cloudshell-user@ip-10-0-180-32 ~]$

**Comment by ShreyT-hash** [comment]
Issue was that the AWS EC2 CLI was being used through the AWS console as opposed to CLI on local machine for deployment.
